### ISSUE TITLE
Display doesn't always render correctly, depending on screen size

### ISSUE THREAD

**Issue by ArrayBolt3** [lubuntu-team/installer-prompt#1]
OS: Lubuntu Kinetic Kudu 22.10 Alpha.
Hardware: GNOME Boxes virtual machine, SeaBIOS, 16 GB RAM, 128 GB disk space.

Issue:
On some screen sizes, the "Try Lubuntu" and "Install Lubuntu" buttons don't always show up in exactly the right spot. This is very pronounced in a GNOME Boxes VM, as the screen size is dependent on the window size and therefore the resolution may be non-standard.

Steps to reproduce:
1: Clone the installer-prompt repository.
2: Open the CMakeLists.txt file in the repo using Qt Creator (via "Open Project..."), then configure the project.
3: Go to "Edit", then "lubuntu-installer-prompt [master]" > "lubuntu-installer-prompt" > "Source Files" > "installerprompt.cpp", and change line 13 (the one that starts with "QPixmap bg" so that it points to "../installer-prompt/img/background.png", this allows it to work correctly from within a testing environment.
4: Build the project, then launch the "build-installer-prompt-Desktop-Debug/lubuntu-installer-prompt" executable it generates.

Expected results:
lubuntu-installer-prompt launches, and the buttons are in sensible locations.

Actual results:
lubuntu-installer-prompt launches, but the buttons may be in weird locations depending on your screen size.

Notes:
Other render problems may occur depending on the screen size - for instance, on a 1024x768 screen, the bottom of the screen displays part of the top of the background. The program renders perfectly on a 1920x1080 screen, and displays almost right on a 1600x900 screen (the buttons slightly overlap the center ring on 1600x900).

**Comment by tsimonq2** [comment]
I almost wonder if we should switch the background back to the default so we don't have to worry about scaling, unless of course you have an idea on how to fix it

**Comment by ArrayBolt3** [comment]
I don't think we need to scale everything half so much as just ensure the buttons end up in sensible locations no matter the screen size (and also make the background render properly). I'm thinking, move the buttons to the exact middle of the screen vertically - that should look nice no matter what the buttons are covering. Maybe we'll also need something like a black zone behind the blue icons (make the edges fuzzy by blending them to alpha as they go outward), so that no matter where the icons end up, they'll look nice. I'll hack around with the code and see what I can come up with (though I don't know much C++ so don't expect any miracles!).

**Comment by tsimonq2** [comment]
I think this was superseded quite a bit ago?
